/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/card.glb --transform 
Files: ./src/assets/card.glb [161.1KB] > D:\suman-shrestha\card-transformed.glb [26.45KB] (84%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/card-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['suman_id_(1)'].geometry} material={materials['suman_id (1)']} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/card-transformed.glb')
